# tasks file for insync
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ insync_dependencies }}"
  tags:
    - insync-install-dependencies
