# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - insync
    - insync-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - insync
    - insync-install
