# tasks file for insync
---
- name: add public key
  apt_key:
    id: 76D78F0500D026C4
    url: https://d2t3ff60b2tol4.cloudfront.net/services@insynchq.com.gpg.key
    state: present
  tags:
    - insync-repository-public-key

- name: add insync repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ insync_repositories }}"
  tags:
    - insync-repository-add
