# tasks file
---
- name: repository | install dependencies (pre)
  ansible.builtin.apt:
    name: "{{ insync_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - insync-repository-install-dependencies

- name: repository | (keyrings) directory | create
  ansible.builtin.file:
    path: "{{ insync_keyring_dst | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - insync-repository-keyrings-directory-create

- name: repository | (keyring) file | download
  ansible.builtin.apt_key:
    id: "{{ insync_keyring_id }}"
    keyserver: "{{ apt_key_keyserver | default('keyserver.ubuntu.com') }}"
    keyring: "{{ insync_keyring_dst }}"
    state: present
  tags:
    - insync-repository-keyring-file-download

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
    mode: 0644
  with_items: "{{ insync_repositories }}"
  tags:
    - insync-repository-add
