# tasks file
---
- name: repository | dependencies
  apt:
    name: "{{ insync_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - insync-repository-dependencies

- name: repository | add public key
  apt_key:
    id: A684470CACCAF35C
    keyserver: keyserver.ubuntu.com
    state: present
  tags:
    - insync-repository-public-key

- name: repository | add
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ insync_repositories }}"
  tags:
    - insync-repository-add
