# tasks file for insync
---
- name: add public key
  apt_key:
    id: A684470CACCAF35C
    keyserver: keyserver.ubuntu.com
    state: present
  tags:
    - insync-repository-public-key

- name: add insync repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ insync_repositories }}"
  tags:
    - insync-repository-add
